source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.8"
gem "jekyll-seo-tag", "~> 2.8"

# Windows / JRuby timezone data (harmless elsewhere).
gem "tzinfo-data", platforms: [:windows, :jruby]
